# Generated by Django 3.0.2 on 2020-01-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTv_p3auZIO-jK7XWsgmAOwOLrSL7GcJ4JT1CQsdJl391lPu8vj&s'),
        ),
    ]
