# Generated by Django 3.0.2 on 2020-01-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.CharField(max_length=100),
        ),
    ]
